language: python

# NOTE: This is the official workaround to get python 3.7 working.
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
sudo: required
dist: xenial

python:
  - "3.7"

before_install:
  - pip install flake8
  - pip install pylint

install:
  - pip install -r requirements.txt

script:
  - flake8 seabird
  - pylint seabird
  - python -m pytest
