language: python

python:
  - "3.7"

before_install:
  - pip install flake8
  - pip install pylint

install:
  - pip install -r requirements.txt

script:
  - flake8 seabird
  - pylint seabird
  - python -m pytest
